import Head from "next/head";
import { Carousel, Col, Container, Form, Image, Row } from "react-bootstrap";
import Navigation from "./Navigation";
import styles from "../styles/Booking.module.css";

export default function Booking() {
  return (
    <>
      <Head>
        <title>Booking Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navigation />
      <Carousel fade className={styles.carouselFixed}>
        <Carousel.Item>
          <Image
            className="d-block w-100"
            src="/plane.jpeg"
            alt="First slide"
          />
        </Carousel.Item>
        <Carousel.Item>
          <Image
            className="d-block w-100"
            src="/train.jpeg"
            alt="Second slide"
          />
        </Carousel.Item>
        <Carousel.Item>
          <Image className="d-block w-100" src="/bus.jpeg" alt="Third slide" />
        </Carousel.Item>
      </Carousel>
      <Form className={[styles.bookingForm, "p-5 rounded"].join(" ")}>
        <div className="text-center">
          <h1>Book Your Ticket</h1>
          <p>Select your Journey List</p>
        </div>
        <Container>
          <Row>
            <Form.Group className="col-md-6 mb-3">
              <Form.Label>Name</Form.Label>
              <Form.Control type="text" placeholder="Enter name" required />
            </Form.Group>

            <Form.Group className="col-md-6 mb-3">
              <Form.Label>Email</Form.Label>
              <Form.Control type="email" placeholder="Enter email" required />
            </Form.Group>
          </Row>
          <Row>
            <Form.Group className="col-md-6 mb-3">
              <Form.Label>From</Form.Label>
              <Form.Select>
                <option selected>Enter source</option>
                <option value="Barisal">Barisal</option>
                <option value="Chittagong">Chittagong</option>
                <option value="Dhaka">Dhaka</option>
                <option value="Khulna">Khulna</option>
                <option value="Mymensingh">Mymensingh</option>
                <option value="Rajshahi">Rajshahi</option>
                <option value="Rangpur">Rangpur</option>
                <option value="Sylhet">Sylhet</option>
              </Form.Select>
            </Form.Group>

            <Form.Group className="col-md-6 mb-3">
              <Form.Label>To</Form.Label>
              <Form.Select>
                <option selected>Enter destination</option>
                <option value="Barisal">Barisal</option>
                <option value="Chittagong">Chittagong</option>
                <option value="Dhaka">Dhaka</option>
                <option value="Khulna">Khulna</option>
                <option value="Mymensingh">Mymensingh</option>
                <option value="Rajshahi">Rajshahi</option>
                <option value="Rangpur">Rangpur</option>
                <option value="Sylhet">Sylhet</option>
              </Form.Select>
            </Form.Group>
          </Row>
          <Row>
            <Form.Group className="col-md-6 mb-3" controlId="formBasicPassword">
              <Form.Label>Phone Number</Form.Label>
              <Form.Control type="number" placeholder="Enter phone Number" />
            </Form.Group>
            <Form.Group className="col-md-6 mb-3" controlId="formBasicPassword">
              <Form.Label>Date</Form.Label>
              <Form.Control type="date" placeholder="date" />
            </Form.Group>
          </Row>
          <button className="w-100 btn btn-warning" type="submit">
            Book Now
          </button>
        </Container>
      </Form>
    </>
  );
}
